---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-IMP-HTTP
no_index:
  directory:
    - t
    - inc
requires:
  Net::IMP: 0.617
  Net::Inspect: 0.27
resources:
  repository: https://github.com/noxxi/p5-net-imp-http
version: 0.523
